### ISSUE TITLE
Consider adding a schema version to the FT manifest format

### ISSUE THREAD

**Issue by AlCutter** [transparency-dev/armored-witness#90]
If we want to add/change fields in the future it'd be good to have an explicit schema version to switch on.

**Comment by mhutchinson** [comment]
I was going to raise another issue but I think it makes sense to hijack this one. Before release we should declare some version of the manifest v1. Before doing that we want to look at the whole structure and see if it should be refactored. See https://github.com/transparency-dev/armored-witness-applet/pull/227 for an example of a possible change.

**Comment by mhutchinson** [comment]
The manifest file now contains everything that we need in order to reproduce all of the component builds. We're also as far away from release as we're going to be. So now is the best time to consider refactoring the manifest.

Original (https://api.transparency.dev/armored-witness-firmware/ci/log/1/seq/00/00/00/00/87):
```
{
  "component": "TRUSTED_OS",
  "git_tag_name": "0.3.1708084771-incompatible",
  "git_commit_fingerprint": "ecbf4015d81d074df685782bc33c749852159a59",
  "firmware_digest_sha256": "sbrgLKQq4oc44zTDPnGEU5vfqhCof68sH1yVLgsIb48=",
  "tamago_version": "1.21.5",
  "build_envs": [
    "LOG_ORIGIN=transparency.dev/armored-witness/firmware_transparency/ci/1",
    "LOG_PUBLIC_KEY=transparency.dev-aw-ftlog-ci+f5479c1e+AR6gW0mycDtL17iM2uvQUThJsoiuSRirstEj9a5AdCCu",
    "APPLET_PUBLIC_KEY=transparency.dev-aw-applet-ci+3ff32e2c+AV1fgxtByjXuPjPfi0/7qTbEBlPGGCyxqr6ZlppoLOz3",
    "OS_PUBLIC_KEY1=transparency.dev-aw-os1-ci+7a0eaef3+AcsqvmrcKIbs21H2Bm2fWb6oFWn/9MmLGNc6NLJty2eQ",
    "OS_PUBLIC_KEY2=transparency.dev-aw-os2-ci+af8e4114+AbBJk5MgxRB+68KhGojhUdSt1ts5GAdRIT1Eq9zEkgQh",
    "BEE=1",
    "DEBUG=1"
  ]
}
```

A proposal:
```
{
  "component": "TRUSTED_OS",
  “git”: {
    "tag_name": "0.3.1708084771-incompatible",
    "commit_fingerprint": "ecbf4015d81d074df685782bc33c749852159a59"
  },
  “build”: {
    "tamago_version": "1.21.5",
    "envs": [
      "LOG_ORIGIN=transparency.dev/armored-witness/firmware_transparency/ci/1",
      "LOG_PUBLIC_KEY=transparency.dev-aw-ftlog-ci+f5479c1e+AR6gW0mycDtL17iM2uvQUThJsoiuSRirstEj9a5AdCCu",
      "APPLET_PUBLIC_KEY=transparency.dev-aw-applet-ci+3ff32e2c+AV1fgxtByjXuPjPfi0/7qTbEBlPGGCyxqr6ZlppoLOz3",
      "OS_PUBLIC_KEY1=transparency.dev-aw-os1-ci+7a0eaef3+AcsqvmrcKIbs21H2Bm2fWb6oFWn/9MmLGNc6NLJty2eQ",
      "OS_PUBLIC_KEY2=transparency.dev-aw-os2-ci+af8e4114+AbBJk5MgxRB+68KhGojhUdSt1ts5GAdRIT1Eq9zEkgQh",
      "BEE=1",
      "DEBUG=1"
  ]
  },
  “output”: {
    "firmware_digest_sha256": "sbrgLKQq4oc44zTDPnGEU5vfqhCof68sH1yVLgsIb48="
  }
}
```

Advantages of this proposal:
 - Clearer grouping of inputs / build process / outputs
 - Using nested structure allows simpler naming (e.g. `git.tag_name` instead of `git_tag_name`)
 - Easier to reason about migration in the future. e.g. we could swap the whole `git` block for a different block that defines where the code is stored

**Comment by AlCutter** [comment]
Noice.
Shall we just add the schema version to the top-level of your proposal?
